package edu.utsa.fileflow.cfg;

import org.antlr.v4.runtime.ParserRuleContext;

/**
 * This class holds information about a flow point in the control flow graph
 * such as the type, tokens or statements.
 * 
 * @author Rodney Rodriguez
 *
 */
public class FlowPointContext {

	// ParserRuleContext type generated by ANTLR
	private ParserRuleContext ctx;
	// type of flow point for type casting by the compiler
	private FlowPointContextType type;
	// some flow points can have ctx as null, this field replaces the
	// ctx.getText()
	private String text;

	public FlowPointContext(String text) {
		this.ctx = null;
		this.text = text;
		this.type = FlowPointContextType.FlowPoint;
	}

	public FlowPointContext(String text, FlowPointContextType type) {
		this.ctx = null;
		this.text = text;
		this.type = type;
	}

	public FlowPointContext(ParserRuleContext ctx, FlowPointContextType type) {
		this.ctx = ctx;
		this.type = type;
	}

	public ParserRuleContext getContext() {
		return ctx;
	}

	public FlowPointContextType getType() {
		return type;
	}

	public String getText() {
		if (ctx == null)
			return text;
		return ctx.getText();
	}

}
