####################
# CASE 0: PASS
####################
#
#touch file1
#
#===================
# Precondition:
#	-file1
#
# Postcondition:
#	+file1
#===================


####################
# CASE 1: PASS
####################
#
#touch file1
#touch file1
#
#===================
# Precondition:
#	-file1
# 
# Postcondition:
# +file1
#
# Warnings: 
#	file1 exists
#===================


####################
# CASE 2: PASS
####################
#
#rm file1
#
#===================
# Precondition:
#	+file1
# 
# Postcondition:
#	-file1
#===================


####################
# CASE 3: PASS
####################
#
#rm file1
#rm file1
#
#===================
# cannot remove 'file1': No such file or directory
#===================


####################
# CASE 4: PASS
####################
#
# touch file1
# rm file1
# touch file1
#
#===================
# Precondition:
#	-file1
#
# Postcondition:
#	+file1
#===================
