####################
# CASE 0: PASS
####################
#
#touch file1
#
#===================
# Precondition:
#	-file1
#
# Postcondition:
#	+file1
#===================


####################
# CASE 1: PASS
####################
#
#touch file1
#touch file1
#
#===================
# Precondition:
#	-file1
# 
# Postcondition:
# +file1
#
# Warnings: 
#	file1 exists
#===================


####################
# CASE 2: PASS
####################
#
#rm file1
#
#===================
# Precondition:
#	+file1
# 
# Postcondition:
#	-file1
#===================


####################
# CASE 3: PASS
####################
#
#rm file1
#rm file1
#
#===================
# cannot remove 'file1': No such file or directory
#===================


####################
# CASE 4: PASS
####################
#
#touch file1
#rm file1
#touch file1
#
#===================
# Precondition:
#	-file1
#
# Postcondition:
#	+file1
#===================


####################
# CASE 5: PASS
####################
#
#mkdir dir1
#
#===================
# Precondition:
#	-dir1/
#
# Postcondition:
#	+dir1/
#===================

####################
# CASE 6: PASS
####################
#
#mkdir dir1
#mkdir dir1
#
#===================
# CompilerException: FileException: mkdir: cannot create directory 'dir1': File exists
#===================


####################
# CASE 7: PASS
####################
#
#mkdir dir1
#touch dir1/file1
#
#===================
# Precondition:
#	-dir1/file1
#
# Postcondition:
#	+dir1/file1
#===================


####################
# CASE 8: PASS
####################
#
#mkdir dir1/dir2
#
#===================
# Precondition:
#	-dir1/dir2
#
# Postcondition:
#	+dir1/dir2
#===================


####################
# CASE 9: PASS
####################
#
#mkdir dir1
#touch dir1/file1
#rm dir1/file1
#
#===================
# Precondition:
#	-dir1/file1
#
# Postcondition:
#	+dir1/
#	-dir1/file1
#===================


####################
# CASE 10: FAIL
####################
#
rm dir1/file1
#
#===================
# Precondition:
#	+dir1/file1
#
# Postcondition:
#	-dir1/file1
# 
# NOTES: dir1 should exist in post but does not
#===================